### ISSUE TITLE
Error while interacting with the peers

### ISSUE THREAD

**Issue by alejandrolr** [IBM/blockchain-network-on-kubernetes#1]
I have deployed the entire network properly (using minikube), but when I access to one peer (example org1peer1) I get this error while interacting with the blockchain:
```
~/kubernetes_fabric/blockchain-network-on-kubernetes$ kubectl exec -it blockchain-org1peer1-74f9fb4b8f-6ql84 bash

root@blockchain-org1peer1-74f9fb4b8f-6ql84:/# peer chaincode query -C channel1 -n cc -c '{"Args":["query","a"]}'
Error: Error getting endorser client chaincode: PER:404 - Error trying to connect to local peer
/opt/gopath/src/github.com/hyperledger/fabric/peer/common/common.go:116 github.com/hyperledger/fabric/peer/common.GetEndorserClient
/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/common.go:240 github.com/hyperledger/fabric/peer/chaincode.InitCmdFactory
/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/query.go:57 github.com/hyperledger/fabric/peer/chaincode.chaincodeQuery
/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode/query.go:35 github.com/hyperledger/fabric/peer/chaincode.queryCmd.func1
/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:599 github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).execute
/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:689 github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).ExecuteC
/opt/gopath/src/github.com/hyperledger/fabric/vendor/github.com/spf13/cobra/command.go:648 github.com/hyperledger/fabric/vendor/github.com/spf13/cobra.(*Command).Execute
/opt/gopath/src/github.com/hyperledger/fabric/peer/main.go:118 main.main
/opt/go/src/runtime/proc.go:192 runtime.main
/opt/go/src/runtime/asm_amd64.s:2087 runtime.goexit
Caused by: context deadline exceeded
2018-03-08 11:20:47.536 UTC [grpc] Printf -> DEBU 001 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 10.102.98.21:30110: operation was canceled"; Reconnecting to {blockchain-org1peer1:30110 <nil>}
Usage:
  peer chaincode query [flags]
... (CONTINUE THE HELP)
```

Do you know a possible reason of getting this issue?

Thank you!!

**Comment by maheshwarishikha** [comment]
Error says, "Error getting endorser client chaincode". Looks like chaincode is not installed properly. Could you please check the logs of all pods to be sure if there is any error during setup.
P.S: I have not tried locally using minikube so not sure whether same scripts will work as-is.

**Comment by maheshwarishikha** [comment]
Did you check logs? any error in pod logs?

**Comment by alejandrolr** [comment]
thank you maheshwarishikha, I will see the logs..., but I think is a communication problem with grpc, but I will double check it and comment here my conclusions!!

**Comment by rajeshlc** [comment]
Got same issue setting up locally Kubernetes(minikube). 
Workaround is to set CORE_PEER_ADDRESS=0.0.0.0:30110 in peer node bash and run peer commands.
Further checking if CORE_PEER_ADDRESSAUTODETECT=true set on peers is causing this.

$ kubectl exec -it blockchain-org1peer1-74f9fb4b8f-rplhn bash

root@blockchain-org1peer1-74f9fb4b8f-rplhn:/# CORE_PEER_ADDRESS=0.0.0.0:30110

root@blockchain-org1peer1-74f9fb4b8f-rplhn:/# peer chaincode query -C channel1 -n cc -c '{"Args":["query","a"]}'
2018-03-13 15:47:15.899 UTC [msp] GetLocalMSP -> DEBU 001 Returning existing local MSP
2018-03-13 15:47:15.899 UTC [msp] GetDefaultSigningIdentity -> DEBU 002 Obtaining default signing identity
2018-03-13 15:47:15.899 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 003 Using default escc
2018-03-13 15:47:15.899 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 004 Using default vscc
2018-03-13 15:47:15.900 UTC [msp/identity] Sign -> DEBU 005 Sign: plaintext: 0A92070A6408031A0C0883E59FD50510...120263631A0A0A0571756572790A0161 
2018-03-13 15:47:15.900 UTC [msp/identity] Sign -> DEBU 006 Sign: digest: 9D3A461AF381387B134C56960914B876B88588E18C50211DE84EAB4FB14AFDDA 
Query Result: 100
2018-03-13 15:47:15.914 UTC [main] main -> INFO 007 Exiting.....
root@blockchain-org1peer1-74f9fb4b8f-rplhn:/#

**Comment by maheshwarishikha** [comment]
Good catch @rajeshlc . Thanks for your help here.

@alejandrolr , it will work for you now. Hence closing the issue.
