### ISSUE TITLE
Files in persistent volumes disappear

### ISSUE THREAD

**Issue by kevinmilliganpartners** [IBM/blockchain-network-on-kubernetes#14]
At various points at the execution, it seems like the files in the persistent volumes disappear, leading to issues mainly in create channel and join channel. When these issues arise, a "describe pod" call for the respective job almost always contains the line "Pod sandbox changed, it will be killed and recreated." Here is the output of "kubectl describe utils" (the generateartifacts job):

Events:
  Type    Reason                 Age   From                                               Message
  ----    ------                 ----  ----                                               -------
  Normal  SuccessfulMountVolume  1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  MountVolume.SetUp succeeded for volume "shared-pv"
  Normal  SuccessfulMountVolume  1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  MountVolume.SetUp succeeded for volume "dockersocket"
  Normal  SuccessfulMountVolume  1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  MountVolume.SetUp succeeded for volume "default-token-g8n9w"
  Normal  Scheduled              1m    default-scheduler                                  Successfully assigned utils-ljqvg to gke-cluster-1-default-pool-49fc0de8-5sp6
  Normal  Pulling                1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  pulling image "hyperledger/fabric-tools:x86_64-1.0.4"
  Normal  Created                1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  Created container
  Normal  Pulled                 1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  Successfully pulled image "hyperledger/fabric-tools:x86_64-1.0.4"
  Normal  Created                1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  Created container
  Normal  Started                1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  Started container
  Normal  Pulled                 1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  Successfully pulled image "hyperledger/fabric-tools:x86_64-1.0.4"
  Normal  Pulling                1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  pulling image "hyperledger/fabric-tools:x86_64-1.0.4"
  Normal  Started                1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  Started container
  Normal  Pulling                1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  pulling image "hyperledger/fabric-tools:x86_64-1.0.4"
  Normal  Pulled                 1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  Successfully pulled image "hyperledger/fabric-tools:x86_64-1.0.4"
  Normal  Created                1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  Created container
  Normal  Started                1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  Started container
  Normal  SandboxChanged         1m    kubelet, gke-cluster-1-default-pool-49fc0de8-5sp6  Pod sandbox changed, it will be killed and re-created.

What causes the collapse of the sandbox, and how can I fix this issue?

**Comment by maheshwarishikha** [comment]
Hi, are you trying using IBM Cloud Container Service? Also, is it happening everytime for you?

**Comment by kevinmilliganpartners** [comment]
No, I'm actually using Google Cloud Platform. Are there compatibility issues? Yes, the same error appears, but not always in the generateartifacts job, sometimes it happens in create channel and join channel.

**Comment by maheshwarishikha** [comment]
It looks to be Kubernetes issue. There should not be any compatibility issue as such but you can try following approaches:
1. Try reaching out to google cloud support if they can provide you some reason for this.
2. Try once on IBM Cloud in free tier plan and check if you find same issue.

**Comment by kevinmilliganpartners** [comment]
Thanks for the suggestions. I wasn't able to create a cluster on my free account, so I'm using the $200 credit from the upgraded account. I freshly downloaded the files into another directory, but I'm still getting this error from create channel: 

kubectl logs createchannel-b98d2 createchanneltx
/shared
bootstrap
keepalived
2018-07-10 15:45:39.814 UTC [common/configtx/tool] main -> INFO 001 Loading configuration
2018-07-10 15:45:39.814 UTC [common/configtx/tool/localconfig] Load -> CRIT 002 Error reading configuration:  Unsupported Config Type ""
2018-07-10 15:45:39.814 UTC [common/configtx/tool] func1 -> ERRO 003 Could not find configtx.yaml. Please make sure that FABRIC_CFG_PATH is set to a path which contains configtx.yaml
