### ISSUE TITLE
hyperledger-fabric: error: [client-utils.js]: sendPeersProposal

### ISSUE THREAD

**Issue by shyrazkhan** [IBM/blockchain-network-on-kubernetes#15]
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: Failed to deserialize creator identity, err The supplied identity is not valid, Verify() returned x509: certificate signed by unknown authority.

Facing this issue while accessing chaincode on kubernetes via nodejs api.

var fabric_client = new Fabric_Client();

// setup the fabric network    
var channel = fabric_client.newChannel('channel1');
var peer = fabric_client.newPeer('grpc://184.172.247.100:30317');
channel.addPeer(peer);

const request = {
   chaincodeId: 'tunacc',
   txId: tx_id,
   fcn: 'queryAllTuna',
   args: ['']
   };

// send the query proposal to the peer
return channel.queryByChaincode(request);   //this line through an exception.

when i can execute chaincode within org1peer1 container it is working fine. but through node.js api it wont work.kubernetes services working snapshot https://i.stack.imgur.com/B187L.png

**Comment by maheshwarishikha** [comment]
@shyrazkhan , I am also hitting the same error. Working on it.

@alejandrolr , as you said before it worked fine for you. Could you please help here.

Enroll and register is working fine but query/invoke is failing with following error:
"Verify() returned x509: certificate signed by unknown authority"
Any idea, how to fix this.

Thanks in advance.

**Comment by shyrazkhan** [comment]
@maheshwarishikha , Thanks... I am stuck  here from last two weeks still didn't find any solution.

**Comment by alejandrolr** [comment]
Hi! I didn't face that problem, I set up my own kubernetes cluster and then I used the fabcar 1.0 node SDK example without problem.

I suggest to check the version 1.0 in all components, and set up the fabric-ca properly in enroll and register (using CA1 or CA2 depending on the org):
```
fabric_ca_client = new Fabric_CA_Client('http://104.197.110.202:30054', tlsOptions , 'CA1', crypto_suite);
```

Regards!!

**Comment by alejandrolr** [comment]
I think that this problem is caused because you need to indicate the CA name, CA1 or CA2 as I mentioned before.

**Comment by shyrazkhan** [comment]
Hi alejandrolr, thanks for your reply. I have tried your solution but still facing the same issue. I am sharing Org1Peer1 logging at the time when facing an exception.

![image](https://user-images.githubusercontent.com/11777006/43099428-9a8676c8-8edb-11e8-8977-78c11861a827.png)

**Comment by shyrazkhan** [comment]
Here is logging while admin and user1 enroll and register with CA Server..

![image](https://user-images.githubusercontent.com/11777006/43099680-592dce82-8edc-11e8-9670-36e7c0627efd.png)



![image](https://user-images.githubusercontent.com/11777006/43099726-802325e6-8edc-11e8-8f59-2af4a9a36651.png)

**Comment by alejandrolr** [comment]
It's strange... I don't know the reason. It worked fine for me, I used the fabcar-1.0 example:

Change these lines in enroll.js:
```
fabric_ca_client = new Fabric_CA_Client('http://blockchain-ca:30054', tlsOptions , 'CA1', crypto_suite);
```
In invoke.js
```
// setup the fabric network
var channel = fabric_client.newChannel('channel1');
var peer = fabric_client.newPeer('grpc://blockchain.org1peer1:30110');
channel.addPeer(peer);
var order = fabric_client.newOrderer('grpc://blockchain-orderer:31010')
channel.addOrderer(order);

..(more code)..
        var request = {
                //targets: let default to the peer assigned to the client
                chaincodeId: 'yourccName',
                fcn: 'yourFuncName',
                args: ['arg1','arg2'],
                chainId: 'channel1',
                txId: tx_id
         };

(more...)

event_hub.setPeerAddr('grpc://blockchain-org1peer1:30111');
```

**Comment by alejandrolr** [comment]
And make sure that you have opened all these ports in your cluster.

**Comment by maheshwarishikha** [comment]
@alejandrolr , opened these ports in cluster -- means create services for these ports...right? or some extra step for that?

**Comment by alejandrolr** [comment]
When you create a kubernetes cluster, it is created in some cloud instances. So if you define a service you have to expose it externally and open ports in your cloud firewall rules. Otherwise, you cannot access to your service even if created.

**Comment by alejandrolr** [comment]
What kind of cloud server are you using? 
I've deployed my cluster in google (GKE), so I've created a firewall rule to allow this traffic in my instances in these ports.
Looking at your photos I can see that you are using IBM cloud, so you must have a similar firewall panel on it.

**Comment by shyrazkhan** [comment]
Hi @alejandrolr  thanks, your previous solution worked for me... i was mistakenly enroll with CA instead of CA1 or CA2 

Thanks again.

**Comment by maheshwarishikha** [comment]
@shyrazkhan , Can you please tell me more detail...what change worked for you? It is not working for me.

 fabric_ca_client = new Fabric_CA_Client('http://< ip >:30054', tlsOptions , '', crypto_suite);  -- it worked for me without CA name. But as you mentioned we need to give CA name, so tried that. But it failed with error saying - "ca1 does not exist".

Then I added ca name as an environment to ca container. After this following command worked:
 fabric_ca_client = new Fabric_CA_Client('http://< ip >:30054', tlsOptions , 'CA1', crypto_suite);

But query/invoke is still failing.

**Comment by shyrazkhan** [comment]
@maheshwarishikha ... i just passed a parameter value "CA1" instead of " ", then it worked for me..
I am sharing my working code here.

fabric_ca_client = new Fabric_CA_Client('http://<ip>:30818/', tlsOptions , 'CA1', crypto_suite);

Below code to make connection and query to org1peer1...

var channel = fabric_client.newChannel('channel1');
var peer = fabric_client.newPeer('grpc://<ip>:32590');
channel.addPeer(peer);

**Comment by maheshwarishikha** [comment]
@shyrazkhan , I notice (in the snapshots provided) that you are using IBM Cloud, did you do any step related to open/expose ports?

**Comment by shyrazkhan** [comment]
@maheshwarishikha , Yes I'm using IBM bluemix for kubernetes and yes you need to expose your deployment PORTS externally by using this kubectl command:

kubectl expose deployment/<your_deployment_name> --type=NodeType --port=<your_container_port> --name=<external_service_name> --target-port=<your_container_port>

**Comment by maheshwarishikha** [comment]
@shyrazkhan , this exposing port is equivalent to create services for those ports as defined in https://github.com/IBM/blockchain-network-on-kubernetes/blob/master/configFiles/blockchain-services.yaml 

Right? Are you doing this as an extra step. 
When I try the command given by you on commandline, I got -

$ kubectl expose deployment/blockchain-org1peer1 --type=NodePort --port=30110 --name blockchain-org1peer1 --target-port=30110
Error from server (AlreadyExists): services "blockchain-org1peer1" already exists

**Comment by maheshwarishikha** [comment]
Finally it worked for me as well. Issue was with cacerts. Now it is working, hence closing the issue. Thanks.
