### ISSUE TITLE
failed to execute transaction: timeout expired while executing transaction

### ISSUE THREAD

**Issue by lotty02cho** [IBM/blockchain-network-on-kubernetes#20]
I try to run this project by using minikube.

I just have made my minikube cluster, and I ran the codes line by line.

when `./setup_blockchainNetwork.sh` start to join channel.

It just comes out `Waiting for chaincodeinstantiatejob to be completed`  in terminal like infinite loop.

and I enter minikube dashboard and I found Job categories, my 'joinchannel' job doesn't work well.

log is written like `Error: Error endorsing chaincode: rpc error: code = Unknown desc = failed to execute transaction: timeout expired while executing transaction`.

How can I solve my issues? does anyone know about it?

**Comment by maheshwarishikha** [comment]
Plz check https://github.com/IBM/blockchain-network-on-kubernetes/issues/1 - it talks about some issue while trying with minikube. Let me know if it helps.

**Comment by lotty02cho** [comment]
Yeah, I checked it and it works. Thanks.
