### ISSUE TITLE
How do I connect different physical computers?

### ISSUE THREAD

**Issue by lotty02cho** [IBM/blockchain-network-on-kubernetes#21]
I try to run this project by using minikube.

I can run this project with own my computer.

but there is one thing I want to ask. I want to connect 6 physical computers(which will be org1, org2, .. org6). 

If I want to run this project using 6 physical computers? How can I do? like.. changing ports or change configtx.yaml something like that.

Please let me know. Thanks for helping me, in advance.

**Comment by maheshwarishikha** [comment]
Closing this issue now, open a new issue or reopen this one if you still have any question. Thanks.
