### ISSUE TITLE
How to enable couch DB?

### ISSUE THREAD

**Issue by rajBandhakavi** [IBM/blockchain-network-on-kubernetes#23]
I have used this open source project to implement a blockchain network on Kubernetes. Could you please let me know how to enable couch DB for this network so that I can perform some rich Queries?

**Comment by maheshwarishikha** [comment]
Hi @rajBandhakavi , for couch DB - need to create one pod for couch db and associate the same with the peers pod.

**Comment by rajBandhakavi** [comment]
yes. I did the same. thank you for letting me know because your reply acts as a conformation.
