### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer dereference while setting up fabric env

### ISSUE THREAD

**Issue by SakivV** [IBM/blockchain-network-on-kubernetes#26]
Hi Team,

While setting up the Fabric Env. on Kubernetes.

Cryptogen Starts
total 20
drwxr-xr-x. 3 1001 99 4096 Nov 3 12:55 chaincode
-rw-r--r--. 1 1001 99 7827 Nov 3 12:45 configtx.yaml
-rw-r--r--. 1 1001 99 4433 Nov 3 12:44 crypto-config.yaml
org1.main.tcloud.kpn.org
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6a2280]

Can you please guide here.

**Comment by maheshwarishikha** [comment]
@SakivV , which version of Kubernetes you are using? Also, are you using IBM kubernetes service on IBM Cloud?
Tested the same with IKS 1.9 and 1.10 on IBM Cloud and it is working fine.

**Comment by maheshwarishikha** [comment]
@SakivV , did it work for you?

**Comment by SakivV** [comment]
@maheshwarishikha Yes it's working. Actually while running Cryptogen I mentioned wrong directory path. After changing path it worked.
