### ISSUE TITLE
Cannot run Kubernetes Dashboard

### ISSUE THREAD

**Issue by fenris85** [IBM/blockchain-network-on-kubernetes#30]
Hi, 
I've deployed network on my local machine and it's working fine. I've also tried to use Kubernetes Dashboard but instead of the dashboard at http://localhost:8001 I've got json with paths. Did I make sth wrong?

<img width="439" alt="screen shot 2019-01-18 at 16 46 01" src="https://user-images.githubusercontent.com/603495/51397415-76b66580-1b41-11e9-9f89-3404fdc5c902.png">

**Comment by ConnorChristie** [comment]
You can access the dashboard through the proxy by following this URL format:
`http://localhost:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/`

**Comment by maheshwarishikha** [comment]
@fenris85 , try accessing http://localhost:8001/ui instead of http://localhost:8001
It should work. Thanks.

**Comment by maheshwarishikha** [comment]
@fenris85 , It must have worked for you. Hence closing this issue. If you still have any issue then feel free to reopen or open a new issue. Thanks.
