### ISSUE TITLE
chmod: changing permissions of '/shared/leapd': Operation not permitted

### ISSUE THREAD

**Issue by Hellovolcanoofficial** [IBM/blockchain-network-on-kubernetes#34]
When running setup_blockchainNetworks, It breaks down in Kubernetes on my Docker Desktop and comes out Error like this. It seems the permissions in container is not permitted. And can see logs in sh terminal like this:
![image](https://user-images.githubusercontent.com/16516722/53311859-8ddd3580-38ed-11e9-902c-8db99b70a4eb.png)
Wating for container of copy artifact pod to run. Current status of copyartifacts-9fjh2 is Succeeded
![image](https://user-images.githubusercontent.com/16516722/53311876-a2b9c900-38ed-11e9-8af8-8eb9f1f65b78.png)
![image](https://user-images.githubusercontent.com/16516722/53311885-b36a3f00-38ed-11e9-9552-32406255dbaa.png)

**Comment by Hellovolcanoofficial** [comment]
Well I finally solve this problem by change CreateVolume.yaml hostPath location and give that directory permission for all users to rwx(read write and execute). THX.

**Comment by tle-totalwine** [comment]
Can you share how you solved it?
