### ISSUE TITLE
waiting for artifacts to complete infinitly 

### ISSUE THREAD

**Issue by pikvik** [IBM/blockchain-network-on-kubernetes#35]
After running setup_blockchainNetwork file I am getting endlessly running "waiting for artifacts to complete " 

<img width="1679" alt="screen shot 2019-02-26 at 6 46 41 pm" src="https://user-images.githubusercontent.com/18361946/53415315-ef3cfb80-39f6-11e9-8b3e-0a7b1d2bb5e1.png">

**Comment by maheshwarishikha** [comment]
@pikvik, it means 'kubectl cp' command is not working properly for you. Check the path/artifacts as mentioned in repository.
You can refer this issue https://github.com/IBM/blockchain-network-on-kubernetes/issues/34 if it resolves your problem. Let me know if it helps.

**Comment by gentian0185** [comment]
@pikvik 
Change the picture below.
It looks like an 'jobStatus Print' issue

![setup_blockchainnetwork](https://user-images.githubusercontent.com/5811280/53730069-31b07d80-3eba-11e9-8281-5fbf1cbeec36.png)

**Comment by maheshwarishikha** [comment]
@pikvik, yes it is the issue with latest version of kubectl 1.12+
Need to change in setup_blockchainNetwork.sh script the way I was checking Job Status. Will do it soon. Thanks.

**Comment by maheshwarishikha** [comment]
@pikvik, required code changes are done in repository. It should work seamlessly for you now.
I am closing the issue now. Feel free to reopen or a new if any issue. Thanks.
