### ISSUE TITLE
Plans on moving to fabric 1.4.x?

### ISSUE THREAD

**Issue by mrshah-at-ibm** [IBM/blockchain-network-on-kubernetes#39]
Hyperledger fabric has published v1.3, v1.4.0, v.1.4.1 & v2.0. This repository is still using the fabric version v1.2.1.

Are there any plans to upgrade this repository to move to the latest fabric versions?

**Comment by ljbennett62** [comment]
@mrshah-at-ibm - will you be updating this - otherwise - we will need to retire it.

**Comment by maheshwarishikha** [comment]
@ljbennett62 , @mrshah-at-ibm - I'll update it to 1.4 this week. Thanks.

**Comment by maheshwarishikha** [comment]
It has been upgraded to Fabric1.4. Hence closing the issue. Thanks.
