### ISSUE TITLE
instantiate chaincode error

### ISSUE THREAD

**Issue by greatyaqi** [IBM/blockchain-network-on-kubernetes#51]
Execute the script to deploy hyperledger fabric network.
```
./setup_blockchainNetwork.sh
```
When the script is executed to instantiate the chain code，There is an error here.
![image](https://user-images.githubusercontent.com/11549225/60708397-92bb9100-9f40-11e9-8b1b-01e1af8e11ec.png)

Execute 
```
kubectl get pod
```
![image](https://user-images.githubusercontent.com/11549225/60711191-e7620a80-9f46-11e9-9d51-71808359cd7e.png)
Execute
```
peer chaincode list -C channel1  --installed
```
![image](https://user-images.githubusercontent.com/11549225/60711425-838c1180-9f47-11e9-9cbe-ed7fcbb0c5d8.png)

**Comment by greatyaqi** [comment]
This question has puzzled me for several days.

**Comment by maheshwarishikha** [comment]
@greatyaqi , did u change anything in scripts? If job/pod says..completed/successful....there should not be any error.

**Comment by greatyaqi** [comment]
I am operating on the mac system.

@maheshwarishikha 
![image](https://user-images.githubusercontent.com/11549225/61015880-30d7ad00-a3c0-11e9-9801-0423dff4df66.png)
Execute
```
kubectl get pod
```
![image](https://user-images.githubusercontent.com/11549225/61015923-5a90d400-a3c0-11e9-84ec-d486dc56430e.png)
Execute
```
kubectl logs -f chaincodeinstantiate-hr2wd
```
![image](https://user-images.githubusercontent.com/11549225/61015961-7b592980-a3c0-11e9-8a8f-b98510f0640e.png)

Execute
```
kubectl version --short
```
![image](https://user-images.githubusercontent.com/11549225/61015994-a2176000-a3c0-11e9-806a-a55e268714b5.png)

**Comment by maheshwarishikha** [comment]
@greatyaqi , I notice that your client and server version are 1.10...but you have docker-dind* ... which should be there incase of IKS 1.11.x or greator.
Please refer to step 4 again in the documentation...and retry. It will work. 
Thanks

**Comment by greatyaqi** [comment]
> @greatyaqi , I notice that your client and server version are 1.10...but you have docker-dind* ... which should be there incase of IKS 1.11.x or greator.
> Please refer to step 4 again in the documentation...and retry. It will work.
> Thanks

solved it!
