### ISSUE TITLE
Error in Update Chaincode

### ISSUE THREAD

**Issue by touqeerShah** [IBM/blockchain-network-on-kubernetes#52]
hello 
i am try to change chaincode and try to make sum updated but it will install everything look good and fine but when i query the older chaincode will response no new function where visible

**Comment by maheshwarishikha** [comment]
@touqeerShah , if your changes are reflecting then it may happen with one of the following reason- 
- chaincode is getting instantiated with old chaincode...so try with different version of chaincode or different name and version of chaincode
- if above solution does not work...I'll suggest you to setup the network again
- if still does not work...try in a fresh cluster...
Let me know if u try any of these. Thanks.

**Comment by maheshwarishikha** [comment]
Hope it must have helped and worked for you. Hence closing this issue now. Feel free to re-open or open a new issue if required. Thanks.

**Comment by touqeerShah** [comment]
thank you for you response @maheshwarishikha . i will tried all way we you told above but it not work
