### ISSUE TITLE
Initantiate chaincode error with k8s-1.15.0 and fabric-1.4.1

### ISSUE THREAD

**Issue by im-Angry** [IBM/blockchain-network-on-kubernetes#53]
I use k8s-1.15.0 to depoy fabric-1.4.1 with raft mode，all pods status is ok. When I run fabric-samples/first-network/scripts/script.sh in org1 cli container，instantiate chaincode on peer0.org2 error：【  **could not assemble transaction, err proposal response was not successful, error code 500, msg chaincode registration failed: container exited with 0** 】

FYI:
   all pods status：
[
![allPods](https://user-images.githubusercontent.com/19897979/61195509-0c027300-a6fb-11e9-89f6-dbfbc9b82610.png)
](url)

  cli logs:
[
![cliLog](https://user-images.githubusercontent.com/19897979/61195517-1f154300-a6fb-11e9-84ad-c41160b403ba.png)
](url)

  peer0.org2 logs and env:
[
![peerLog](https://user-images.githubusercontent.com/19897979/61195542-4835d380-a6fb-11e9-9af2-1e15a30ff4f7.png)
](url)

  orderer logs and env:
[
![ordererLog](https://user-images.githubusercontent.com/19897979/61195645-e2961700-a6fb-11e9-8edc-e994378eca06.png)
](url)

  But on single machine with similar config, I use docker-compose or k8s, no errors occurred
  pls, give me some suggestions

**Comment by maheshwarishikha** [comment]
@im-Angry , "k8s-1.15.0 to depoy fabric-1.4.1 with raft mode" - please explain...what do you mean by this?

**Comment by maheshwarishikha** [comment]
@im-Angry , any updates on this?

**Comment by maheshwarishikha** [comment]
@im-Angry , you can check https://github.com/IBM/blockchain-network-on-kubernetes/issues/54 - it might be helpful.

**Comment by maheshwarishikha** [comment]
No updates from a long time. Hope it has worked for you. Closing the issue at this moment, feel free to reopen if it is still not working for you. Thanks
