### ISSUE TITLE
Waiting for chaincodeinstantiate job to be completed :: 

### ISSUE THREAD

**Issue by advissor** [IBM/blockchain-network-on-kubernetes#54]
The step to point to tcp://docker:2375 was performed
## Linux
$ sed -i s#unix:///host/var/run/docker.sock#tcp://docker:2375# configFiles/peersDeployment.yaml

ubuntu@ip-xxxxxxxxxxxxx~/blockchain-network-on-kubernetes$ cat configFiles/peersDeployment.yaml | grep tcp://docker:2375
          value: tcp://docker:2375
          value: tcp://docker:2375
          value: tcp://docker:2375
          value: tcp://docker:2375

Client Version: **v1.13.8**
Server Version: **v1.13.8+IKS**

NAME                                    READY   STATUS      RESTARTS   AGE
blockchain-ca-54d7b4ddfc-jxrzh          1/1     Running     0          14m
blockchain-orderer-67c9ff777d-mpdqm     1/1     Running     0          14m
blockchain-org1peer1-7bd4879446-mqm52   1/1     Running     0          14m
blockchain-org2peer1-8fc4fbcfc-grk2t    1/1     Running     0          14m
blockchain-org3peer1-6cf5d4875f-jn776   1/1     Running     0          14m
blockchain-org4peer1-68699bdd8f-l5dhp   1/1     Running     0          14m
chaincodeinstall-49nq2                  0/4     Completed   0          14m
**chaincodeinstantiate-5llqr              0/1     Error       0          14m
chaincodeinstantiate-gnhpg              0/1     Error       0          14m**
copyartifacts-dtblm                     0/1     Completed   0          15m
createchannel-dwvrl                     0/2     Completed   0          14m
docker-dind-545d6b5986-2l7cz            1/1     Running     0          15m
joinchannel-dh8s6                       0/4     Completed   0          14m
utils-l6s97                             0/2     Completed   0          15m

ubuntu@ip-xxx-xx-x-xx:~/blockchain-network-on-kubernetes$ kubectl logs chaincodeinstantiate-5llqr
2019-07-29 20:36:56.351 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2019-07-29 20:36:56.351 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
**Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error starting container: error starting container: cannot connect to Docker endpoint**

From what I've seen in other older issues, substitution should have helped. But apparently not in my case.

**Comment by advissor** [comment]
Now looking into this. 
6days ago dind package was updated, which enforses TLS and this will result in error : like  

`docker: Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?.`
https://gitlab.com/gitlab-org/gitlab-runner/issues/4501

Will try to test with older "docker:18.09-dind"

**Comment by advissor** [comment]
So, solutions for many people here is to use **docker:18.09-dind** or update files to implement TLS

Chaincode Instantiation Completed Successfully
Chaincode Instantiation Completed Successfully

Network Setup Completed !!
ubuntu@ip-xxxxxxx~/blockchain-network-on-kubernetes$ Chaincode Instantiation Completed Successfully
**---Workaround--**

blockchain-network-on-kubernetes/configFiles/docker.yaml
Line 35 , to be changed to something like :         image: "docker:18.09-dind"

**Comment by maheshwarishikha** [comment]
@advissor , thanks for providing updates. It is really helpful.

**Comment by cryptogab** [comment]
Thanks a lot @advissor

**Comment by woodyjon** [comment]
Hello,

I changed at line 35 to `image: "docker:18.09-dind"` but I still have the same error. "Waiting for chaincodeinstantiate job to be completed" repeating indefinitely until it stops with "Chaincode Instantiation Failed".

My setup:
- locally with minikube
- kubernetes and kubectl v1.15.9 (because of https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)

Has anyone any idea?
While running the _setup_blockchainNetwork.sh_ script, is there a way to see the logs, why the _chaincodeinstantiate_ does not work?


Thank you!
