### ISSUE TITLE
README-cn.md is so outdated ! 中文文档过期了!

### ISSUE THREAD

**Issue by zcqzcg** [IBM/blockchain-network-on-kubernetes#57]
Hi there,
Thanks for this amazing project and I can easily learn how to deploy fabric into a k8s cluster, even in microk8s at my local machine.

At first I was following `README-cn.md` as instruction and I had so many troubles in deploying the samples. Until I got back to the `README.md` which is in English and kept updated, I have found light.

So, just in case if someone else would like to try this project out, and doesn't have to waste valuable time as I did, **PLEASE DON'T REFER TO `README-cn.md` UNTIL IT'S UPDATED.**

Also it will be wonderful if you see this and update cn.md , or if you have to, delete it as good as well.

Thanks a lot for your time,
Merry Chrismas and Happy New Year!
David

--------------------------------------
**中文文档过期了! 不要参照!**

**Comment by maheshwarishikha** [comment]
@zcqzcg , Thanks for pointing it out. I'll try to get it updated soon. Thanks.

**Comment by maheshwarishikha** [comment]
@zcqzcg , It has been updated. Thanks.
