### ISSUE TITLE
chaincodeinstantiate error

### ISSUE THREAD

**Issue by Ailab666666** [IBM/blockchain-network-on-kubernetes#58]
Hi, when I run setup_blockchainNetwork_v2.sh,at last step , chaincodeinstantiate pod can't startup and occur some error :

[34m2020-01-10 05:34:37.212 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001[0m Using default escc
[34m2020-01-10 05:34:37.212 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002[0m Using default vscc
Error: could not assemble transaction, err proposal response was not successful, error code 500, msg error starting container: error starting container: cannot connect to Docker endpoint

**Comment by maheshwarishikha** [comment]
@Ailab666666 , Please check #54 - if it helps.

**Comment by maheshwarishikha** [comment]
@Ailab666666 , I think it worked for you, hence closing the issue. Feel free to reopen or open a new issue if required. Thanks.
