### ISSUE TITLE
when I use hyperledger explorer connect to the network, the channels show [] and the nodes show 2

### ISSUE THREAD

**Issue by Ailab666666** [IBM/blockchain-network-on-kubernetes#59]
@maheshwarishikha 
when I use hyperledger explorer connect to the network, the channels show [] and the nodes show 2,.
the right result should be channels = ['channel1'] and nodes number = 4?

------
1) get channels
/api/channels/info ->

{
    "status": 200,
    "channels": []   // should be ['channel1'] 
}

2)get nodes number
api/status/ ->

{
    "chaincodeCount": "1",
    "txCount": "2",
    "latestBlock": "2",
    "peerCount": "2" // should be 4
}

**Comment by maheshwarishikha** [comment]
@Ailab666666 , yes it should show output as expected. I have not tried with Composer anytime so really not sure about the steps. Do you see any error message or any message which says - "connected with network":)

**Comment by maheshwarishikha** [comment]
I do not see any updates here. Hope it is working now for you. Hence closing the issue, feel free to reopen or open a new issue. Thanks.
