### ISSUE TITLE
Connecting REST Service

### ISSUE THREAD

**Issue by okaara1** [IBM/blockchain-network-on-kubernetes#6]
Hello everybody. Really nice resource. I have successfully deployed the network on Kubernetes. I would like to connect my REST service to communicate with the peers in the cluster. Do you have any idea of how I could do this?

**Comment by maheshwarishikha** [comment]
Good to hear that it was helpful for you. Could you please explain what do you mean by REST service means? Are you talking about composer-rest-server?

**Comment by okaara1** [comment]
I have written a nodejs service that exposes APIs and interacts with a peer using the Fabric Node SDK. By calling the APU you can enroll users, create channels and query/invoke the chaincode. This works locally. I would like to know whether it's possible to set this service also on kubernetes and how to do it.

**Comment by maheshwarishikha** [comment]
I understand that you have written a node js application using fabric node SDK and your application works fine with your local blockchain network. If it is correct, then you just need to update connection details in your app. For connection, use public IP of your kubernetes cluster and the exposed port of your pod.

**Comment by maheshwarishikha** [comment]
Did it work for you?

**Comment by maheshwarishikha** [comment]
@okaara1 , either it has worked for you or you are not working on this these days. Hence closing this issue as iis more than a week now. Feel free to reopen or open new issue if you need any help on it. Thanks.
