### ISSUE TITLE
Error running docker container.. ${dockerPodStatus} never changed to "Running" while executing setup_blockchainNetwork.sh

### ISSUE THREAD

**Issue by jayantaKD** [IBM/blockchain-network-on-kubernetes#60]
I am getting the following error while trying to execute ./setup_blockchainNetwork.sh : 

`error: unable to recognize "/home/jayanta/fabric-samples/blockchain-network-on-kubernetes/configFiles/docker.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"`
and in a infinite loop for waiting for Docker container to run. I am using kubernetes v1.17.

**Comment by maheshwarishikha** [comment]
@jayantaKD , it is because of API changes with the latest version of kubernetes. I'll be updating the repo soon. Thanks.

**Comment by maheshwarishikha** [comment]
@jayantaKD Please take the latest code and retry. I have updated the code repository for the Kubernetes 1.16. It should work now. Thanks.

**Comment by maheshwarishikha** [comment]
@jayantaKD - hope it is working for you. I do not see any update after repo updation....so closing this issue. Feel free to reopen or open a new issue if required. Thanks.
