### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by kylehz** [IBM/blockchain-network-on-kubernetes#61]
```
$ ./setup_blockchainNetwork_v2.sh
...
Generating the required artifacts for Blockchain network
Running: kubectl create -f /Users/kylehz/Downloads/blockchain-network-on-kubernetes/configFiles/generateArtifactsJob.yaml
job.batch/utils created
Waiting for generateArtifacts job to complete
...
Waiting for generateArtifacts job to complete
There is an error in utils job. Please check logs.

$ kubectl get jobs --watch
NAME            COMPLETIONS   DURATION   AGE
copyartifacts   1/1           32s        9m34s
utils           0/1           9m1s       9m1s

$ kubectl get pods | grep utils
utils-95mjv                   1/2     Error       0          9m55s

$ kubectl logs utils-95mjv -c cryptogen
/shared/crypto-config/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp/keystore/0b6f282d23e0b34db1302d9cf707a944e88b341c6205443f745242463e58e132_sk
/shared/crypto-config/peerOrganizations/org4.example.com/users/User1@org4.example.com/msp/keystore
find: ‘/shared/Proxifier-Euz62I’: Permission denied
chmod: changing permissions of '/shared': Operation not permitted
chmod: changing permissions of '/shared/Proxifier-Euz62I': Operation not permitted

$ kubectl version --short
Client Version: v1.15.5
Server Version: v1.17.3
```

**Comment by maheshwarishikha** [comment]
@kylehz , I'll check with this kubectl version and update you. Thanks.

**Comment by maheshwarishikha** [comment]
@kylehz - I did not face this issue when I tried with Kubernetes Service hosted on IBM Cloud. Still you can take the latest code and retry. I have updated the code repository for the Kubernetes 1.16. Let me know if it works for you Thanks.

**Comment by warm3snow** [comment]
@maheshwarishikha - I got the same issue. 
$ k logs utils-9jrd6 cryptogen
/shared/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp/keystore/36235e839138677c476cb1d6b51b7ccf9b8c068db1529a1057f15dd81f54d217_sk
/shared/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp/keystore
chmod: changing permissions of '/shared': Operation not permitted
$ kubectl version --short
Client Version: v1.15.5
Server Version: v1.15.5
I run `./setup_blockchainNetwork_v2.sh` and i have enabled kubernetes in docker-desktop locally.

**Comment by maheshwarishikha** [comment]
@kylehz - hope it worked for you. Closing the issue because of inactivity. Feel free to reopen or open a new issue if required. Thanks.
