### ISSUE TITLE
Is there roadmap for Support for HF 2.1?

### ISSUE THREAD

**Issue by sillysachin** [IBM/blockchain-network-on-kubernetes#72]

**Comment by chebyte** [comment]
+1

**Comment by maheshwarishikha** [comment]
@sillysachin , @chebyte - did u try just changing the fabric images version in yaml files?

**Comment by maheshwarishikha** [comment]
No plans to update. You can refer here - https://ibm-blockchain.github.io/ansible-collection/tutorials/installing.html
Hence closing this issue.
