### ISSUE TITLE
If restart the pods, lose the shared-pvc volume data

### ISSUE THREAD

**Issue by leandrosilvaferreira** [IBM/blockchain-network-on-kubernetes#74]
To test my persistent data, I rebooted my kubernates service and after that, I lost all my data in shared-pvc volume claim.

`root@blockchain-org1peer1-7fddb4c66f-249wj:/# cd /shared/

root@blockchain-org1peer1-7fddb4c66f-249wj:/shared# ls -lah

total 36K

drwxrwxrwt 9 root root 4.0K Jul 21 18:30 .

drwxr-xr-x 1 root root 4.0K Jul 21 18:29 ..

drwxrwxrwt 2 root root 4.0K Jul 21 18:23 .ICE-unix

drwxrwxrwt 2 root root 4.0K Jul 21 18:23 .Test-unix

drwxrwxrwt 2 root root 4.0K Jul 21 18:23 .X11-unix

drwxrwxrwt 2 root root 4.0K Jul 21 18:23 .XIM-unix

drwxrwxrwt 2 root root 4.0K Jul 21 18:23 .font-unix

drwx------ 3 root root 4.0K Jul 21 18:23 systemd-private-28177ba8811e43d490782af54178f0ce-systemd-resolved.service-sZkfkl

drwx------ 3 root root 4.0K Jul 21 18:23 systemd-private-28177ba8811e43d490782af54178f0ce-systemd-timesyncd.service-vA7pNs
`

**Comment by maheshwarishikha** [comment]
@leandrosilvaferreira - No, that should not happen. Are you trying on IBM Cloud? If yes, did you run setup scripts again after rebooting K8 service?

**Comment by maheshwarishikha** [comment]
Closing this issue because of no-activity.
