### ISSUE TITLE
Can it supports fabric2.2

### ISSUE THREAD

**Issue by circlecxz** [IBM/blockchain-network-on-kubernetes#76]

**Comment by maheshwarishikha** [comment]
@circlecxz - I have not tested it with 2.2
You can try after changing the image name in yaml file. Let me know if that works for you. Thanks

**Comment by circlecxz** [comment]
> @circlecxz - I have not tested it with 2.2
> You can try after changing the image name in yaml file. Let me know if that works for you. Thanks

it does not support

**Comment by circlecxz** [comment]
> @circlecxz - I have not tested it with 2.2
> You can try after changing the image name in yaml file. Let me know if that works for you. Thanks
It hangs at "Waiting for generateArtifacts job to complete".. any suggestions please

**Comment by maheshwarishikha** [comment]
No plans to update this for 2.2, hence closing this issue.
