### ISSUE TITLE
Error: failed to create deliver client: orderer client failed to connect to blockchain-orderer

### ISSUE THREAD

**Issue by dev-jb** [IBM/blockchain-network-on-kubernetes#77]
The configuration works fine on single node Kubernetes cluster. I am having a problem while working with multiple Kubernetes cluster. I have to mention the cluster IP of each services as below:
```
hostAliases:
- ip: "xx.xxx.xx.xxx"
         hostnames:
         - "blockchain-orderer"

```
Then only it's able to connect to the service. Is the way of doing this correct? Or am I missing something on Kubernetes itself? How does my services know which IP to use?

**Comment by maheshwarishikha** [comment]
@dev-jb - It is a standard workflow when you use multiple nodes in Kubernetes cluster. I have personally not tried this Blockchain network setup with multiple nodes but this article will surely help.
https://kubernetes.io/docs/concepts/services-networking/service/

Thanks.
