### ISSUE TITLE
could not launch chaincode 'ibcc:5d0e934e1c508fa8ebf14bacc51c47d92780284ceca7edc0788e3b6ce98d1795': chaincode registration failed: container exited with 0

### ISSUE THREAD

**Issue by umeraqeel786** [IBM/blockchain-network-on-kubernetes#79]
**peer logs** 
2021-03-29 06:08:28.712 UTC [endorser] SimulateProposal -> ERRO 048 failed to invoke chaincode ibcc, error: container exited with 0
github.com/hyperledger/fabric/core/chaincode.(*RuntimeLauncher).Launch.func1

**when i invoke the transaction** 
Error: endorsement failure during invoke. response: status:500 message:"error in simulation: failed to execute transaction 7c38e2f08ce510395540a94a3174fb7d6585f55a03e847dbc0188fbbe495d0e4: could not launch chaincode ibcc:5d0e934e1c508fa8ebf14bacc51c47d92780284ceca7edc0788e3b6ce98d1795: chaincode registration failed: container exited with 0"

**Comment by KillerGasy** [comment]
How was this issue resolved?
